name: Production

on:
  push:
    tags:
      - v*

concurrency:
  cancel-in-progress: true
  group: production

jobs:
  ##############################################################################
  ## BUILD AND REGISTER NEXT APP
  ##############################################################################
  register-app:
    name: Build & Register app
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imageName: doc-demo-app/app
          token: ${{ secrets.GITHUB_TOKEN }}
            

  ##############################################################################
  ## DEPLOY
  ##############################################################################
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register-app]
    environment:
      name: production
      url: https://doc-demo-app.fabrique.social.gouv.fr/
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
