name: Review

on: push

jobs:
  ##############################################################################
  ## BUILD AND REGISTER NEXT APP
  ##############################################################################
  register-app:
    name: Build & Register app
    runs-on: ubuntu-latest
    steps:
      - name: Get branch slug and commit sha
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
          echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imageName: doc-demo-app/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            GITHUB_SHA=${{ env.GITHUB_SHA }}

  ##############################################################################
  ## DEPLOY
  ##############################################################################
  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    needs: [register-app]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: "dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
